# Generated by Django 3.0.6 on 2020-07-18 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CurrentLocation', models.CharField(max_length=60)),
                ('Destination', models.CharField(max_length=60)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('passengers', models.PositiveIntegerField()),
                ('smoking', models.BooleanField()),
                ('pets', models.BooleanField()),
                ('music', models.BooleanField()),
                ('rating', models.FloatField()),
                ('user', models.CharField(max_length=60)),
            ],
        ),
    ]
