# Generated by Django 3.0.6 on 2020-07-19 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trips', '0003_remove_trip_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
