# Generated by Django 3.0.6 on 2020-07-19 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trips', '0004_auto_20200719_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='id',
            field=models.CharField(max_length=60, primary_key=True, serialize=False),
        ),
    ]
