# Generated by Django 3.0.6 on 2020-07-19 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trips', '0005_auto_20200719_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='driver_name',
        ),
    ]
