# Generated by Django 3.0.6 on 2020-07-19 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trips', '0007_auto_20200719_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trip',
            name='user',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
