# Generated by Django 3.0.6 on 2020-07-19 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trips', '0008_auto_20200719_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='user',
        ),
    ]
