# Generated by Django 3.0.6 on 2020-07-19 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trips', '0009_remove_trip_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='user',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
