# Generated by Django 3.0.6 on 2020-07-19 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trips', '0010_trip_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='user',
        ),
    ]
